#!/usr/bin/env ruby

# ---------------------------------------------------------------------------
# Import bookmarks from a delicious export file.
# Requires a user id and a path to a file.
# ---------------------------------------------------------------------------

require 'rexml/document'
require 'pp'

# Get the user id.
user_id = ARGV[0]
if user_id.nil?
  puts "A user id must be provided"
  exit
end

# Make sure that we have a valid user.
begin
  user = User.find(user_id)
rescue ActiveRecord::RecordNotFound
  puts "The user id provided is invalid"
  exit
end

# Get the path to the file, and make sure it exists.
import_path = ARGV[1]
unless !import_path.nil? and FileTest.exists?(import_path)
  puts "A file must be provided"
  exit
end

puts "User: #{user.name}"
puts "File: #{import_path}"

# Process the file.
xml, posts = File.read(import_path), []
doc = REXML::Document.new(xml)
doc.elements.each('posts/post') do |s|
  data = {}
  
  # Get the data.
  data['url']         = s.attributes['href']
  data['title']       = s.attributes['description']
  data['description'] = s.attributes['extended']
  data['tag_list']    = s.attributes['tag'].split(' ')
  data['created_at']  = s.attributes['time'].sub('/[TZ]/', ' ')
  
  posts << data
end

posts.reverse.each do |data|
  # Add the entry.
  bookmark = user.bookmarks.build(data)
  bookmark.save
end
